### ISSUE TITLE
Consider moving all fatal connection errors to 4xxxx range?

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-common#6]
Currently, all unrecoverable, client-caused connection errors are in the 4xxxx range, with the exception of 80015, 80017, and 80030. Should we consider making those three 4xxxx errors too, to make the test for connection failure (currently https://github.com/ably/ably-js/blob/fail-and-disconnect/common/lib/transport/connectionmanager.js#L23-L33) simpler? @mattheworiordan @paddybyers  

(80015 ("incompatible connection parameters") and 80030 ("client restriction not satisfied") seem suited to 4x;  80017 ('connection already closed') less so)

**Comment by paddybyers** [comment]
I'd be happy if we have ranges 84xxx with the same fail behaviour as 4xxxx, and 85xxx with the same fail behaviour as 5xxxx.

**Comment by SimonWoolf** [comment]
Overtaken by other discussions (https://github.com/ably/wiki/issues/212#issuecomment-337615165 et at)
